name: Changeset PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changeset:
    # 🚨 prevent loop from release commits
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install deps
        run: npm install

      # IMPORTANT: ONLY create PR, DO NOT version/publish
      - name: Create Changeset PR
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
