name: Deploy Angular to GitHub Pages

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  schedule:
    - cron: "0 0 * * *"


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    if: >
      github.event_name == 'schedule' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 🚨 IMPORTANT: clean install
      - name: Install dependencies
        run: npm install

      # 🚨 CRITICAL: build ALL workspace libs first
      - name: Build packages (monorepo libs)
        run: npm run build --workspaces

      # 🚨 THEN build Angular app
      - name: Build Angular
        run: npm run build:prod

      - name: Add SPA fallback
        run: |
          cp dist/ts-utils-lite-demo/browser/index.html \
             dist/ts-utils-lite-demo/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/ts-utils-lite-demo/browser

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
